version: "3.9"

services:
  db:
    image: postgres:16
    container_name: camping-db
    environment:
      POSTGRES_USER: camping
      POSTGRES_PASSWORD: camping
      POSTGRES_DB: camping
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
